team:
   name: CodeClouders
   members:
      - user: ja.romerog12@uniandes.edu.co
        percentage: 25
      - user: lj.torresm1@uniandes.edu.co
        percentage: 25
      - user: v.castanedap@uniandes.edu.co
        percentage: 25
      - user: k.maldonadod@uniandes.edu.co
        percentage: 25
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/129
user-management:
  folder: msusers
  port: 3000
  authors:
    - ja.romerog12@uniandes.edu.co
post-management:
  folder: posts
  port: 3001
  authors:
    - v.castanedap@uniandes.edu.co
offer-management:
  folder: offers
  port: 3003
  authors:
    - lj.torresm1@uniandes.edu.co
route-management:
  folder: route
  port: 3002
  authors:
    - k.maldonadod@uniandes.edu.co