version: "3.8"

services:
  invoices:
    build: ./invoices/
    ports:
      - "3002:3002"
    environment:
      DB_NAME: monitor_invoice
      DB_HOST: invoice_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      invoice_db:
        condition: service_healthy
    networks:
      - app_net
      - invoice_net

  payments:
    build: ./payments/
    ports:
      - "3001:3001"
    environment:
      DB_NAME: monitor_payment
      DB_HOST: payment_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      payment_db:
        condition: service_healthy
    networks:
      - app_net
      - payment_net
  
  invoice_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_invoice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - invoice_net

  payment_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - payment_net

networks:
  invoice_net:
  payment_net:
  app_net:
