version: "3.8"

services:
  plans:
    build: ./plans/.
    ports:
      - "3003:3003"
    environment:
      DB_NAME: monitor_plans
      DB_HOST: plans_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      USERS_PATH: "http://users:3000"
    depends_on:
      plans_db:
        condition: service_healthy
    networks:
      - app_net
      - plan_net

  plans_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_plans
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - plan_net

networks:
  plan_net:
  app_net:
