version: "3.8"

services:
  users:
    build: ./users/
    ports:
      - "3000:3000"
    environment:
      DB_NAME: monitor_user
      DB_HOST: user_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      user_db:
        condition: service_healthy
    networks:
      - app_net
      - user_net

  invoices:
    build: ./invoices/
    ports:
      - "3002:3002"
    environment:
      DB_NAME: monitor_invoice
      DB_HOST: invoice_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      SENGRID_TOKEN: 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
    depends_on:
      invoice_db:
        condition: service_healthy
    networks:
      - app_net
      - invoice_net

  payments:
    build: ./payments/
    ports:
      - "3001:3001"
    environment:
      DB_NAME: monitor_payment
      DB_HOST: payment_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      payment_db:
        condition: service_healthy
    networks:
      - app_net
      - payment_net
  
  plans:
    build: ./plans/
    ports:
      - "3003:3003"
    environment:
      DB_NAME: monitor_plans
      DB_HOST: plans_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      USERS_PATH: "http://users:3000"
    depends_on:
      plans_db:
        condition: service_healthy
    networks:
      - app_net
      - plan_net
  
  reports:
    build: ./reports/
    ports:
      - "3006:3006"
    environment:
      DB_NAME: monitor_reports
      DB_HOST: reports_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      USERS_PATH: "http://users:3000"
      SENGRID_TOKEN: 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
    depends_on:
      reports_db:
        condition: service_healthy
    networks:
      - app_net
      - reports_net

  incident:
    build: ./incidents/
    ports:
      - "3004:3004"
    environment:
      DB_NAME: monitor_incident
      DB_HOST: incident_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      USERS_PATH: "http://users:3000"
    depends_on:
      incident_db:
        condition: service_healthy
    networks:
      - app_net
      - incident_net

  ia:
    build: ./ia/
    ports:
      - "3005:3005"
    environment:
      DB_NAME: monitor_incident
      DB_HOST: incident_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      USERS_PATH: "http://users:3000"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      incident_db:
        condition: service_healthy
    networks:
      - app_net
      - ia_net

  user_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - user_net

  invoice_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_invoice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - invoice_net

  payment_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - payment_net

  plans_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_plans
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5434:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - plan_net
  
  reports_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_reports
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - reports_net

  incident_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_incident
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - incident_net

networks:
  invoice_net:
  payment_net:
  app_net:
  plan_net:
  incident_net:
  user_net:
  reports_net:
  ia_net:
