version: "3.8"

services:
  invoices:
    build: ./incidents/
    ports:
      - "3004:3004"
    environment:
      DB_NAME: monitor_incident
      DB_HOST: incident_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      incident_db:
        condition: service_healthy
    networks:
      - app_net
      - incident_net
  
  incident_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_incident
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
    - incident_net

networks:
  incident_net:
  app_net: