version: "3.8"
   
services:  
  reports:
    build: .
    ports:
      - "3005:3005"
    environment:
      DB_NAME: monitor_reports
      DB_HOST: reports_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      reports_db:
        condition: service_healthy

  reports_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_reports
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

   