apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-contenedor
          image: us-central1-docker.pkg.dev/experimentos-435400/uniandes-misw-proyecto-grado-19/users:1.0
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3000

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: users-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3000
    type: HTTP
    requestPath: /user/ping

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  annotations:
    cloud.google.com/backend-config: '{"default": "users-config"}'
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32337
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: users-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","r
eason":"ValidMetricFound","message":"the HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"2m"}}]'
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-deployment
  targetCPUUtilizationPercentage: 50
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 1
  desiredReplicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidents-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incidents
  template:
    metadata:
      labels:
        app: incidents
    spec:
      serviceAccountName: k8s-proyecto-final-serviceaccount
      containers:
        - name: incidents-contenedor
          image: us-central1-docker.pkg.dev/experimentos-435400/uniandes-misw-proyecto-grado-19/incidents:1.0
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3004

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: incidents-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3004
    type: HTTP
    requestPath: /incident/ping

---
apiVersion: v1
kind: Service
metadata:
  name: incidents-service
  annotations:
    cloud.google.com/backend-config: '{"default": "incidents-config"}'
spec:
  selector:
    app: incidents
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
      nodePort: 32338
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: incidents-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","r
eason":"ValidMetricFound","message":"the HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"2m"}}]'
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: incidents-deployment
  targetCPUUtilizationPercentage: 50
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 1
  desiredReplicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plans-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plans
  template:
    metadata:
      labels:
        app: plans
    spec:
      serviceAccountName: k8s-proyecto-final-serviceaccount
      containers:
        - name: plans-contenedor
          image: us-central1-docker.pkg.dev/experimentos-435400/uniandes-misw-proyecto-grado-19/plans:1.0
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3003

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: plans-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3003
    type: HTTP
    requestPath: /plan/ping

---
apiVersion: v1
kind: Service
metadata:
  name: plans-service
  annotations:
    cloud.google.com/backend-config: '{"default": "plans-config"}'
spec:
  selector:
    app: plans
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
      nodePort: 32339
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: plans-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","r
eason":"ValidMetricFound","message":"the HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"2m"}}]'
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plans-deployment
  targetCPUUtilizationPercentage: 50
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 1
  desiredReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: invoice
  template:
    metadata:
      labels:
        app: invoice
    spec:
      serviceAccountName: k8s-proyecto-final-serviceaccount
      containers:
        - name: plans-contenedor
          image: us-central1-docker.pkg.dev/experimentos-435400/uniandes-misw-proyecto-grado-19/invoice:1.0
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3002

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: invoice-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3002
    type: HTTP
    requestPath: /invoice/ping

---
apiVersion: v1
kind: Service
metadata:
  name: invoice-service
  annotations:
    cloud.google.com/backend-config: '{"default": "invoice-config"}'
spec:
  selector:
    app: invoice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
      nodePort: 32340
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: invoice-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","r
eason":"ValidMetricFound","message":"the HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"2m"}}]'
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: invoice-deployment
  targetCPUUtilizationPercentage: 50
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 1
  desiredReplicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: k8s-proyecto-final-serviceaccount
      containers:
        - name: plans-contenedor
          image: us-central1-docker.pkg.dev/experimentos-435400/uniandes-misw-proyecto-grado-19/payment:1.0
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3001

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: payment-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3001
    type: HTTP
    requestPath: /payment/ping

---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  annotations:
    cloud.google.com/backend-config: '{"default": "payment-config"}'
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
      nodePort: 32341
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: payment-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","r
eason":"ValidMetricFound","message":"the HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"2m"}}]'
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: payment-deployment
  targetCPUUtilizationPercentage: 50
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 1
  desiredReplicas: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ia-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ia
  template:
    metadata:
      labels:
        app: ia
    spec:
      serviceAccountName: k8s-proyecto-final-serviceaccount
      containers:
        - name: ia-contenedor
          image: us-central1-docker.pkg.dev/experimentos-435400/uniandes-misw-proyecto-grado-19/ia:1.0
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3005

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: ia-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3005
    type: HTTP
    requestPath: /ia/ping

---
apiVersion: v1
kind: Service
metadata:
  name: ia-service
  annotations:
    cloud.google.com/backend-config: '{"default": "ia-config"}'
spec:
  selector:
    app: ia
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3005
      nodePort: 32342
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ia-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","r
eason":"ValidMetricFound","message":"the HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"2m"}}]'
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ia-deployment
  targetCPUUtilizationPercentage: 50
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 1
  desiredReplicas: 1
