apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users-contenedor
          image: us-central1-docker.pkg.dev/experimentos-435400/uniandes-misw-proyecto-grado-19/users:1.0
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3000

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: users-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3000
    type: HTTP
    requestPath: /user/ping

---
apiVersion: v1
kind: Service
metadata:
  name: users-service
  annotations:
    cloud.google.com/backend-config: '{"default": "users-config"}'
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32337
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: users-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","r
eason":"ValidMetricFound","message":"the HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"2m"}}]'
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: users-deployment
  targetCPUUtilizationPercentage: 50
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 1
  desiredReplicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidents-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incidents
  template:
    metadata:
      labels:
        app: incidents
    spec:
      serviceAccountName: k8s-proyecto-final-serviceaccount
      containers:
        - name: incidents-contenedor
          image: us-central1-docker.pkg.dev/experimentos-435400/uniandes-misw-proyecto-grado-19/incidents:1.0
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3004

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: incidents-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3004
    type: HTTP
    requestPath: /incident/ping

---
apiVersion: v1
kind: Service
metadata:
  name: incidents-service
  annotations:
    cloud.google.com/backend-config: '{"default": "incidents-config"}'
spec:
  selector:
    app: incidents
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3004
      nodePort: 32338
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: incidents-hpa
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","r
eason":"ValidMetricFound","message":"the HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"2m"}}]'
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: incidents-deployment
  targetCPUUtilizationPercentage: 50
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 1
  desiredReplicas: 1
