apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "35.202.66.24"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  SENGRID_TOKEN: "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"
  OPENAI_API_KEY: "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"