apiVersion: apps/v1
kind: Deployment
metadata:
  name: plans-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plans
  template:
    metadata:
      labels:
        app: plans
    spec:
      containers:
        - name: plans-contenedor
          image: us-central1-docker.pkg.dev/experimentos-435400/uniandes-misw-proyecto-grado-19/plans:2.0
          envFrom:
            - secretRef:
                name: db-secrets
          ports:
            - containerPort: 3003

---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: plans-config
spec:
  healthCheck:
    checkIntervalSec: 60
    port: 3003
    type: HTTP
    requestPath: /plan/ping

---
apiVersion: v1
kind: Service
metadata:
  name: plans-service
  annotations:
    cloud.google.com/backend-config: '{"default": "plans-config"}'
spec:
  selector:
    app: plans
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
      nodePort: 32337
  type: NodePort

---
# HPA

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    autoscaling.alpha.kubernetes.io/conditions: '[{"type":"AbleToScale","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"ScaleDownStabilized","message":"recent
      recommendations were higher than current one, applying the highest recent recommendation"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2021-12-08T17:22:16Z","r
eason":"ValidMetricFound","message":"the
      HPA was able to successfully calculate a replica count from cpu resource utilization
      (percentage of request)"},{"type":"ScalingLimited","status":"False","lastTransitionTime":"2021-12-08T17:22:16Z","reason":"DesiredWithinRange","message":"the
      desired count is within the acceptable range"}]'
    autoscaling.alpha.kubernetes.io/current-metrics: '[{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":1,"currentAverageValue":"2m"}}]'
  name: plans-hpa
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: plans-deployment
  targetCPUUtilizationPercentage: 10
status:
  currentCPUUtilizationPercentage: 1
  currentReplicas: 1
  desiredReplicas: 1
  