apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
  DB_HOST: "35.202.66.24"
  DB_PORT: "5432"
  DB_NAME: "postgres"
  SENGRID_TOKEN: "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"
  OPENAI_API_KEY: "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"