version: "3.8"
   
services:  
  users:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_NAME: monitor_user
      DB_HOST: user_db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      user_db:
        condition: service_healthy

  user_db:
    image: postgres
    environment:
      POSTGRES_DB: monitor_user
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5

   