name: Deploy ABCall

on:
  push:
    branches:
    - 'github-actions'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2
    
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Export gcloud related env variable
      run: export CLOUDSDK_PYTHON="/usr/bin/python3"

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        export_default_credentials: true

    - name: Get the latest image version
      id: get-version
      run: | 
        IMAGE_TAG: ${{ github.run_number }}
        echo "Latest version: $IMAGE_TAG"

    #    TAGS=$(gcloud container images list-tags us-central1-docker.pkg.dev/$GOOGLE_PROJECT/uniandes-misw-proyecto-grado-19/plans --format='get(tags)') 
    #    LATEST_VERSION=$(echo "$TAGS" | grep -Eo '([0-9]+\.[0-9]+)' | sort -V | tail -n 1)
    #    echo "Latest version: $LATEST_VERSION"

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/uniandes-misw-proyecto-grado-19/plans:3.0 ./plans
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/uniandes-misw-proyecto-grado-19/plans:3.0
